api/v1/views/account.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from api.v1.forms.user_account_forms import RegisterForm, LoginForm

accounts_bp = Blueprint("accounts", __name__)


# Added the view for Registering a user
@accounts_bp.route('/register', methods=["GET", "POST"], strict_slashes=False)
def register():
    if current_user.is_authenticated:
        flash("You are already logged in.", "info")
        return redirect(url_for("home"))
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        from models.user import User
        from models import storage
        users = [user for user in storage.all(User).values() if user.email == form.email.data]
        user = users[0] if users else None
        if user:
            flash("Email already exists!", "danger")
            return render_template("/register.html", form=form)
        user = User(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data,
            cohort=form.cohort.data,
            password=form.password.data
        )
        storage.new(user)
        storage.save()

        login_user(user)
        flash("You registered and are now logged in. Welcome!", "success")

        return redirect(url_for("core.home"))
    return render_template("/register.html", form=form)


# Added the view for User Login
@accounts_bp.route("/login", methods=["GET", "POST"], strict_slashes=False)
def login():
    if current_user.is_authenticated:
        flash("You are already logged in.", "info")
        return redirect(url_for("core.home"))
    form = LoginForm(request.form)
    if form.validate_on_submit():
        from models import storage
        from models.user import User
        users = [user for user in storage.all(User).values() if user.email == form.email.data]
        user = users[0] if users else None
        from api.v1.app import bcrypt
        if user and bcrypt.check_password_hash(user.password, request.form["password"]):
            login_user(user)
            return redirect(url_for("core.home"))
        else:
            flash("Invalid email and/or password.", "danger")
            return render_template("/login.html", form=form)
    return render_template("/login.html", form=form)

@accounts_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You were logged out.", "success")
    return redirect(url_for("core.home"))

api/v1/views/blogs.py
#!venv/bin/python3
"""USER RESTFul API Definitions"""
from flask import Blueprint, abort, jsonify, render_template, request


blog_bp = Blueprint("blogs", __name__)

@blog_bp.route('/write', methods=['GET'], strict_slashes=False)
def write():
    """API Renders the Write Page"""
    return render_template("write.html")


@blog_bp.route('/blogs', methods=['GET'], strict_slashes=False)
def fetch_all_blogs():
    """API Fetches all blogs in DB"""
    from models import storage
    from models.blog import Blog
    blogs = []
    for blog in storage.all(Blog).values():
        blog_dict = blog.to_dict()
        comments = []
        for comment in blog.comments:
            comment_dict = comment.to_dict()
            comment_dict['responses'] = [
                response.to_dict() for response in comment.responses]
            comments.append(comment_dict)
        blog_dict['comments'] = comments
        blogs.append(blog_dict)
    return jsonify(blogs)


@blog_bp.route('/users/<user_id>/blogs',
                 methods=['GET'], strict_slashes=False)
def fetch_all_user_blogs(user_id):
    """API Fetches all blogs by user_id in DB"""
    from models import storage
    from models.blog import User
    user = storage.get(User, user_id)
    if not user:
        abort(404)
    blogs = [blog.to_dict() for blog in user.blogs]
    return jsonify(blogs)


@blog_bp.route('/blogs/<blog_id>', methods=['GET'], strict_slashes=False)
def fetch_blog(blog_id):
    """API Fetches Blog object by id"""
    from models import storage
    from models.blog import Blog
    blog = storage.get(Blog, blog_id)
    if not blog:
        abort(404)
    return jsonify(blog.to_dict())


@blog_bp.route('/blogs/<blog_id>',
                 methods=['DELETE'], strict_slashes=False)
def delete_blog(blog_id):
    """API deletes Blog object by id"""
    from models import storage
    from models.blog import Blog
    blog = storage.get(Blog, blog_id)
    if not blog:
        abort(404)
    storage.delete(blog)
    storage.save()
    return jsonify({}), 200


@blog_bp.route('/users/<user_id>/blogs',
                 methods=['POST'], strict_slashes=False)
def create_blog(user_id):
    """API creates a new Blog object in DB"""
    from models import storage
    from models.blog import Blog
    from models.user import User
    user = storage.get(User, user_id)
    if not user:
        abort(404)
    if not request.get_json():
        abort(400, 'Not a JSON')
    if 'title' not in request.get_json():
        abort(400, 'Missing title')
    if 'content' not in request.get_json():
        abort(400, 'Missing content')
    attributes = request.get_json()
    blog = Blog(**attributes)
    blog.user_id = user_id
    storage.new(blog)
    storage.save()
    return jsonify(blog.to_dict()), 201


@blog_bp.route('/blogs/<blog_id>',
                 methods=['PUT'], strict_slashes=False)
def update_blog(blog_id):
    """API updates Blog object by id"""
    from models.user import User
    from models import storage
    from models.blog import Blog
    blog = storage.get(Blog, blog_id)
    if not blog:
        abort(404)
    if not request.get_json():
        abort(400, 'Not a JSON')
    attributes = request.get_json()
    for key, value in attributes.items():
        if key not in ['id', 'user_id', 'created_at', 'updated_at']:
            setattr(User, key, value)
        blog.save()
        return jsonify(blog.to_dict()), 200

api/v1/views/index.py
#!venv/bin/python3
from flask import Blueprint, flash, redirect, render_template, url_for

core_bp = Blueprint("core", __name__)


@core_bp.route('/', strict_slashes=False)
def home():
    """Returns Home Page"""
    blogs = []
    from models import storage
    from models.blog import Blog
    for blog in storage.all(Blog).values():
        blog_dict = blog.to_dict()
        comments = []
        for comment in blog.comments:
            comment_dict = comment.to_dict()
            comment_dict['responses'] = [
                response.to_dict() for response in comment.responses]
            comments.append(comment_dict)
        blog_dict['comments'] = comments
        blogs.append(blog_dict)
    return render_template("home.html", blogs=blogs)


@core_bp.route('/post/<blog_id>')
def post(blog_id):
    # Find the blog with the specified ID
    from models import storage
    from models.blog import Blog
    selected_blog = storage.get(Blog, blog_id)

    if selected_blog:
        return render_template('post.html', blog=selected_blog)
    else:
        # Handle case where blog with specified ID is not found
        flash("Falled to Load Blog...", "danger")
        return redirect(url_for("home"))


@core_bp.route('/about', strict_slashes=False)
def about():
    """Returns About Page"""
    return render_template("about.html")

api/v1/templates/_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Walkithot | Home</title>
    <!-- Favicon -->
    <link rel="icon" type="image/png" sizes="32x32" href="./assets/images/favicon.png">
    <!-- Remix icons -->
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
    <!-- Swiper.js styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/swiper-bundle.min.css') }}">
    <!-- Bootstrap -->
    <!--<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">-->
    <!-- Custom styles -->
    <link rel="stylesheet" href="{{ url_for('static',   filename='css/main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',   filename='css/loginstyles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',   filename='css/writestyles.css') }}">
    {% block css %}{% endblock %}
</head>

<body>

    {% include "navbar.html" %}

    <div class="container">
        <br>

        <!-- messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                {% for category, message in messages %}
                <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                    {{message}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
            <div class="col-md-4"></div>
        </div>
        {% endif %}
        {% endwith %}

        <!-- child template -->
        {% block content %}{% endblock %}

    </div>

    <!-- Footer -->
    <footer id="sticky-footer" class="footer section" style="text-align: center">
        <div class="container text-center">
            <small>Copyright &copy;2023 Walkithot. All rights reserved.</small>
        </div>
    </footer>

    <!-- Swiper.js -->
    <script src="../static/script/swiper-bundle.min.js"></script>
    <!-- Custom script -->
    <script src="../static/script/main.js"></script>

</body>

</html>

api/v1/templates/about.html
{% extends "_base.html" %}
{% block content %}

<section class="blog-post section-header-offset">
    <div class="blog-post-container container">
        <div class="blog-post-data">
            <h3 class="title blog-post-title">About Walkithot Blog</h3>
            <div class="article-data">
                <span>Dec 6th 2023</span>
                <span class="article-data-spacer"></span>

            </div>
            <img src="../static/images/featured/featured-1.jpg" alt="">
        </div>

        <div class="container">
            <p>Welcome to Walkithot, the pulsating heart of knowledge and community spirit in the ALX ecosystem. Born
                from the shared passion and camaraderie of three visionaries during their transformative journey at ALX,
                Walkithot is not just a blog; it's a testament to the power of collaboration and the thirst for
                continuous learning.

            </p>

            <p>Picture this: Three friends, immersed in the dynamic world of ALX, identified a gap in the learning
                experience—a gap filled with questions, uncertainties, and the need for a guiding light. With a spark of
                inspiration, Walkithot was born to be that guiding light. It's a vibrant tapestry woven with the threads
                of experience, challenges, victories, and the unquenchable thirst for knowledge.</p>

            <blockquote class="quote">
                <p><span><i class="ri-double-quotes-l"></i></span> As ALX students, we understand the challenges that
                    newcomers face—questions about assignments, the curriculum, and the vast world of technology.
                    Walkithot becomes the virtual companion, offering insights, tips, and shared experiences to smoothen
                    the learning curve for our fellow ALXians.<span><i class="ri-double-quotes-r"></i></span></p>
            </blockquote>

            <p>But Walkithot is not confined to the walls of ALX. It extends its welcoming arms to all tech enthusiasts
                on a quest for knowledge. Our blog is a treasure trove where experiences are shared, mistakes are
                dissected, and victories are celebrated. It's a sanctuary for those navigating the ever-evolving
                landscape of technology.</p>

            <div class="author d-grid">

                <div class="author-about">
                    <h3 class="author-name">Oyebamiji Opeyemi, Kwabena Frimpong, Seyi Ogunmusire</h3>
                    <p>Join us in this journey of discovery, as Walkithot becomes more than a blog—it becomes a
                        community, a mentor, and a friend. Together, let's unravel the mysteries of learning, one blog
                        post at a time.</p>
                    <!-- <ul class="list social-media">
                        <li class="list-item">
                            <a href="#" class="list-link"><i class="ri-instagram-line"></i></a>
                        </li>
                        <li class="list-item">
                            <a href="#" class="list-link"><i class="ri-facebook-circle-line"></i></a>
                        </li>
                        <li class="list-item">
                            <a href="#" class="list-link"><i class="ri-twitter-line"></i></a>
                        </li>
                    </ul> -->
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

api/v1/templates/home.html
{% extends "_base.html" %}
{% block content %}

<div class="featured-articles section section-header-offset">
    <div class="featured-articles-container container d-grid">
        <div class="featured-content d-grid">
            {% for blog in blogs %}
            <a href="{{ url_for('core.post', blog_id=blog.id) }}"
                class="article featured-article featured-article-1 p-5">
                <img src="../static/images/featured/featured-1.jpg" alt="" class="article-image">
                <span class="article-category">{{ blog.category }}</span>

                <div class="article-data-container">

                    <div class="article-data">
                        <span>{{ blog.created_at }}</span>
                        <span class="article-data-spacer"></span>
                    </div>

                    <h3 class="title article-title">{{ blog.title }}</h3>

                </div>
            </a>
            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}

api/v1/templates/login.html
{% extends "_base.html" %}

{% block content %}

<div class="containerlogin">
    <form action="" method="post" role="form" class="admin-form auth-form">
        {{ form.csrf_token }}
        <h1 class="center form=title">Please sign in</h1>

        <div>
            {{ form.email.label }}
            {{ form.email() }}

            {% if form.email.errors %}
            {% for error in form.email.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <div>
            {{ form.password.label }}
            {{ form.password() }}
            {% if form.password.errors %}
            {% for error in form.password.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <div class="form-wrapper">
            <!--<div class="input-group_2">
                <input type="checkbox" name="remember-me" id="remember-me">
                <label for="remember-me">Remember me</label>
            </div>-->
            <div class="forgot-password-wrapper">
                <small><a href="./forgotpassword.html">Forgot Password?</a></small>
            </div>
        </div>

        <div class="input-group">
            <button type="submit" class="btn long-btn primary-btn big-btn">Login</button>
        </div>

        <p class="center">
            <small>Don't yet have an account? <a href="{{ url_for('accounts.register') }}">Register now</a></small>
        </p>
    </form>

</div>

{% endblock %}

api/v1/templates/navbar.html
<!-- Navbar -->
<header class="header" id="header">
    <nav class="navbar container">
        <a href="{{ url_for('core.home') }}">
            <h2 class="logo">Walkithot</h2>
        </a>

        <div class="menu" id="menu">
            <ul class="list">
                <li class="list-item">
                    <a href="{{ url_for('core.home') }}" class="list-link current">Home</a>
                </li>
                <li class="list-item">
                    <a href="{{ url_for('core.about') }}" class="list-link">About</a>
                </li>
                <li class="list-item">
                    <a href="https://github.com/KayFrimp/WalkiThot_v1" target="_blank" class="list-link">Github Repo</a>
                </li>
                {% if current_user.is_authenticated %}
                <li class="list-item">
                    <a href="{{ url_for('blogs.write') }}" class="list-link">Write</a>
                </li>
                {% endif %}
                {% if current_user.is_authenticated %}
                <li class="list-item screen-lg-hidden">
                    <a href="{{ url_for('accounts.logout') }}"><button type="button"
                            class="btn btn-danger me-2">Logout</button></a>
                </li>
                {% else %}
                <li class="list-item screen-lg-hidden">
                    <a href="{{ url_for('accounts.login') }}" class="list-link">Log in</a>
                </li>
                <li class="list-item screen-lg-hidden">
                    <a href="{{url_for('accounts.register') }}" class="list-link">Sign up</a>
                    <!-- </a>/signup.html" class="list-link">Sign up</a> -->
                </li>
                {% endif %}
            </ul>
        </div>

        <div class="list list-right">
            <button class="btn place-items-center" id="theme-toggle-btn">
                <i class="ri-sun-line sun-icon"></i>
                <i class="ri-moon-line moon-icon"></i>
            </button>

            <button class="btn place-items-center" id="search-icon">
                <i class="ri-search-line"></i>
            </button>

            <button class="btn place-items-center screen-lg-hidden menu-toggle-icon" id="menu-toggle-icon">
                <i class="ri-menu-3-line open-menu-icon"></i>
                <i class="ri-close-line close-menu-icon"></i>
            </button>
            {% if current_user.is_authenticated %}
            <a href="{{ url_for('accounts.logout') }}"><button type="button"
                    class="btn btn-danger me-2">Logout</button></a>
            {% else %}
            <a href="{{ url_for('accounts.login') }}" class="list-link screen-sm-hidden">Log in</a>
            <a href="{{url_for('accounts.register') }}" class="btn sign-up-btn fancy-border screen-sm-hidden">
                <span>Sign up</span>
            </a>
            {% endif %}

        </div>

    </nav>
</header>

api/v1/templates/post.html
{% extends "_base.html" %}
{% block content %}

<section class="blog-post section-header-offset">
    <div class="blog-post-container container">
        <div class="blog-post-data">
            <h3 class="title blog-post-title">{{ blog.title }}</h3>
            <div class="article-data">
                <span>{{ blog.created_at }}</span>
                <span class="article-data-spacer"></span>

            </div>
            <img src="../static/images/featured/featured-1.jpg" alt="">
        </div>

        <div class="container">
            <span>
                {{ blog.content }}
            </span>

            <div class="author d-grid">
                <div class="author-image-box">
                    <img src="../static/images/author.jpg" alt="" class="article-image">
                </div>
                <div class="author-about">
                    <ul class="list social-media">
                        <li class="list-item">
                            <a href="#" class="list-link"><i class="ri-instagram-line"></i></a>
                        </li>
                        <li class="list-item">
                            <a href="#" class="list-link"><i class="ri-facebook-circle-line"></i></a>
                        </li>
                        <li class="list-item">
                            <a href="#" class="list-link"><i class="ri-twitter-line"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

api/v1/templates/register.html
{% extends "_base.html" %}

{% block content %}

<div class="containerlogin">
    <h2>Create an Account</h2>
    <form id="signupForm" role="form" method="post">
        {{ form.csrf_token }}

        <div>
            {{ form.first_name.label }}
            {{ form.first_name(class="form-control") }}
            {% if form.first_name.errors %}
            {% for error in form.first_name.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <div>
            {{ form.last_name.label }}
            {{ form.last_name() }}
        </div>
        <div>
            {{ form.email.label }}
            {{ form.email(class="form-control") }}
            {% if form.email.errors %}
            {% for error in form.email.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <div>
            {{ form.password.label }}
            {{ form.password() }}
            {% if form.password.errors %}
            {% for error in form.password.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <div>
            {{ form.confirm.label }}
            {{ form.confirm() }}
            {% if form.confirm.errors %}
            {% for error in form.confirm.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
            {% endfor %}
            {% endif %}
        </div>

        <button class="btn btn-lg" type="submit">Sign Up</button>
    </form>
    <p class="center">
        <small>Already have an account? <a href="{{ url_for('accounts.login') }}">Login now</a></small>
    </p>
</div>

{% endblock %}

api/v1/templates/write.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Walkithot | Write</title>

    <!-- Include TinyMCE from CDN -->
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

    <!-- Initialize TinyMCE -->
    <script>
        tinymce.init({
            selector: '#content',  // Replace 'content' with the ID of your textarea
            height: 300,
            plugins: 'link',
            toolbar: 'undo redo | formatselect | bold italic | alignleft aligncenter alignright alignjustify | link',
        });
    </script>
</head>

<body>
    {% extends "_base.html" %}
    {% block content %}

    <div class="write_container">
        <h1>Write a Blog Post</h1>
        <form id="blogForm">
            <input type="text" id="title" placeholder="Title" name="title"><br><br>
            <hr class="styled-line">
            <!-- Replace the textarea with TinyMCE editor -->
            <textarea id="content" name="content" placeholder="Write your blog" rows="8" cols="50"></textarea><br><br>
        </form>
    </div>

    {% endblock %}
</body>

</html>